### ISSUE TITLE
support Laravel 5.5

### ISSUE THREAD

**Issue by zaherg** [nilportugues/laravel5-hal-json-transformer#6]
Hey,

since the Service provider check for the laravel version, and till today it does not support v5.5, do you have any plan to do so?

thanks

**Comment by behemphi** [comment]
Same problem now but with Laravel 5.6

**Comment by zaherg** [comment]
clearly, the project is dead, and tbh I ended up building my own package.

**Comment by nilportugues** [comment]
It is not dead...
